### ISSUE TITLE
Reviews Accordion

### ISSUE THREAD

**Issue by lambeboluwatife** [lambeboluwatife/lbdflix#14]
The movie reviews are truncated and when clicked it doesn't show the remaining text. 
![image](https://github.com/lambeboluwatife/lbdflix/assets/40843759/c0b46112-b231-4819-baa2-7116637faf70)

**Comment by kmahesh18** [comment]
@lambeboluwatife assign me

**Comment by lambeboluwatife** [comment]
@kmahesh18 it has been assigned to you

**Comment by kmahesh18** [comment]
npm run dev is automatically terminating... is there any issue here other than review accordion

**Comment by lambeboluwatife** [comment]
you can check the site or the codebase for issues. and as for the npm run dev terminating, I don't know about that, it hasn't happened before.
