### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by lambeboluwatife** [lambeboluwatife/lbdflix#15]
The API key needs to be in an env file.

**Comment by Himanshuraj2918** [comment]
Hello, can i solve this problem ??

**Comment by Himanshuraj2918** [comment]
Api key will add in env file so it will not visible to anyone because .env is gitignore file.

**Comment by lambeboluwatife** [comment]
> Hello, can i solve this problem ??
> 

Yes, you can
I'll assign it to you

**Comment by lambeboluwatife** [comment]
> Api key will add in env file so i will not visible to anyone because .env is gitignore file.
> 

Okay
Awesome 
Thanks

**Comment by lambeboluwatife** [comment]
@Himanshuraj2918 why did you close the pull request you made?
