### ISSUE TITLE
Write an Article on how to retrieve an API from TMDB 

### ISSUE THREAD

**Issue by codexive-zech** [lambeboluwatife/lbdflix#24]
Each developer contributing to the project will need to get their designated API key from TMDB and add to .env file. So the article with be a step by step guide showing contributors how to get their API key and add to the.env file.

**Comment by KishanVyas308** [comment]
#24 issue - solution

I'd be glad to assist you with crafting an article tailored to guide contributors on obtaining their TMDB API key and integrating it into the project's .env file. Here's the breakdown:

Title: Securely Accessing TMDB Data: A Guide for Contributors

Introduction:

Briefly introduce the TMDB API and its role in the project (e.g., retrieving movie data).
Emphasize the importance of using individual API keys for security and rate limits.
Obtaining Your TMDB API Key:

Create a TMDB Account:

Direct contributors to the TMDB website (https://www.themoviedb.org/) and guide them to create a free account.
Navigate to API Settings:

After logging in, instruct them to access their account settings and locate the "API" section.
Generate Your API Key:

Explain that they should click on the "Create API Key" button (or similar option based on TMDB's interface).
Briefly mention that TMDB may require agreeing to their terms of use before issuing the key.
Adding the API Key to the .env File:

Locate the .env File:

Inform contributors that the .env file is typically located in the project's root directory.
If the file doesn't exist, they may need to create it (consult project-specific instructions for creation guidance).
Set the TMDB_API_KEY Environment Variable:

Instruct them to add the following line to the .env file, replacing YOUR_API_KEY with their actual API key obtained in step 3 of the previous section:
TMDB_API_KEY=YOUR_API_KEY
Emphasize the importance of keeping the API key private (not committing it to version control).
Additional Considerations (Optional):

Briefly touch upon rate limits and responsible API usage (if relevant to your project).
Mention where the API key is used within the project (if appropriate).
Conclusion:

Reiterate the importance of following these steps to ensure secure and successful use of the TMDB API.
Offer assistance (e.g., through a designated communication channel) if contributors encounter any difficulties.
Remember:

Replace placeholders like https://www.themoviedb.org/ with the actual URL for TMDB's website.
Adapt the instructions based on your project's specific .env file location and variable naming conventions.
Consider adding screenshots or visuals to enhance clarity (if permitted by your documentation guidelines).

i used this api in one of my project. 
this is all apis you need for this project

const requests = {
    requestMovie: https://api.themoviedb.org/3/movie/popular?api_key=(your api key)&language=en-US&page=1,

    requestTrending: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=5,

    requestTV: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=2,
    PopularPeople: https://api.themoviedb.org/3/trending/tv/week?api_key=(your api key)&language=en-US&page=7,

    UpComing: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=4
}

export default requests;

**Comment by codexive-zech** [comment]
> #24 issue - solution
> 
> I'd be glad to assist you with crafting an article tailored to guide contributors on obtaining their TMDB API key and integrating it into the project's .env file. Here's the breakdown:
> 
> Title: Securely Accessing TMDB Data: A Guide for Contributors
> 
> Introduction:
> 
> Briefly introduce the TMDB API and its role in the project (e.g., retrieving movie data). Emphasize the importance of using individual API keys for security and rate limits. Obtaining Your TMDB API Key:
> 
> Create a TMDB Account:
> 
> Direct contributors to the TMDB website (https://www.themoviedb.org/) and guide them to create a free account. Navigate to API Settings:
> 
> After logging in, instruct them to access their account settings and locate the "API" section. Generate Your API Key:
> 
> Explain that they should click on the "Create API Key" button (or similar option based on TMDB's interface). Briefly mention that TMDB may require agreeing to their terms of use before issuing the key. Adding the API Key to the .env File:
> 
> Locate the .env File:
> 
> Inform contributors that the .env file is typically located in the project's root directory. If the file doesn't exist, they may need to create it (consult project-specific instructions for creation guidance). Set the TMDB_API_KEY Environment Variable:
> 
> Instruct them to add the following line to the .env file, replacing YOUR_API_KEY with their actual API key obtained in step 3 of the previous section: TMDB_API_KEY=YOUR_API_KEY Emphasize the importance of keeping the API key private (not committing it to version control). Additional Considerations (Optional):
> 
> Briefly touch upon rate limits and responsible API usage (if relevant to your project). Mention where the API key is used within the project (if appropriate). Conclusion:
> 
> Reiterate the importance of following these steps to ensure secure and successful use of the TMDB API. Offer assistance (e.g., through a designated communication channel) if contributors encounter any difficulties. Remember:
> 
> Replace placeholders like https://www.themoviedb.org/ with the actual URL for TMDB's website. Adapt the instructions based on your project's specific .env file location and variable naming conventions. Consider adding screenshots or visuals to enhance clarity (if permitted by your documentation guidelines).
> 
> i used this api in one of my project. this is all apis you need for this project
> 
> const requests = { requestMovie: https://api.themoviedb.org/3/movie/popular?api_key=(your api key)&language=en-US&page=1,
> 
> ```
> requestTrending: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=5,
> 
> requestTV: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=2,
> PopularPeople: https://api.themoviedb.org/3/trending/tv/week?api_key=(your api key)&language=en-US&page=7,
> 
> UpComing: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=4
> ```
> 
> }
> 
> export default requests;

I love the way you brokedown the steps and crafted the flow of the article, though a few changes can be made so it just be strictly to this open source project. 

If you don't mind it would be cool to work on the article with you.

Either way this is me just appreciating you for the article breakdown u just helped to relief some part of the outline and their process

**Comment by lambeboluwatife** [comment]
> #24 issue - solution
> 
> I'd be glad to assist you with crafting an article tailored to guide contributors on obtaining their TMDB API key and integrating it into the project's .env file. Here's the breakdown:
> 
> Title: Securely Accessing TMDB Data: A Guide for Contributors
> 
> Introduction:
> 
> Briefly introduce the TMDB API and its role in the project (e.g., retrieving movie data).
> Emphasize the importance of using individual API keys for security and rate limits.
> Obtaining Your TMDB API Key:
> 
> Create a TMDB Account:
> 
> Direct contributors to the TMDB website (https://www.themoviedb.org/) and guide them to create a free account.
> Navigate to API Settings:
> 
> After logging in, instruct them to access their account settings and locate the "API" section.
> Generate Your API Key:
> 
> Explain that they should click on the "Create API Key" button (or similar option based on TMDB's interface).
> Briefly mention that TMDB may require agreeing to their terms of use before issuing the key.
> Adding the API Key to the .env File:
> 
> Locate the .env File:
> 
> Inform contributors that the .env file is typically located in the project's root directory.
> If the file doesn't exist, they may need to create it (consult project-specific instructions for creation guidance).
> Set the TMDB_API_KEY Environment Variable:
> 
> Instruct them to add the following line to the .env file, replacing YOUR_API_KEY with their actual API key obtained in step 3 of the previous section:
> TMDB_API_KEY=YOUR_API_KEY
> Emphasize the importance of keeping the API key private (not committing it to version control).
> Additional Considerations (Optional):
> 
> Briefly touch upon rate limits and responsible API usage (if relevant to your project).
> Mention where the API key is used within the project (if appropriate).
> Conclusion:
> 
> Reiterate the importance of following these steps to ensure secure and successful use of the TMDB API.
> Offer assistance (e.g., through a designated communication channel) if contributors encounter any difficulties.
> Remember:
> 
> Replace placeholders like https://www.themoviedb.org/ with the actual URL for TMDB's website.
> Adapt the instructions based on your project's specific .env file location and variable naming conventions.
> Consider adding screenshots or visuals to enhance clarity (if permitted by your documentation guidelines).
> 
> i used this api in one of my project. 
> this is all apis you need for this project
> 
> const requests = {
>     requestMovie: https://api.themoviedb.org/3/movie/popular?api_key=(your api key)&language=en-US&page=1,
> 
>     requestTrending: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=5,
> 
>     requestTV: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=2,
>     PopularPeople: https://api.themoviedb.org/3/trending/tv/week?api_key=(your api key)&language=en-US&page=7,
> 
>     UpComing: https://api.themoviedb.org/3/trending/tv/day?api_key=(your api key)&language=en-US&page=4
> }
> 
> export default requests;
> 

This is awesome and I love it. Can you and @codexive-zech collaborate on this to make it more detailed and awesome 😎.

**Comment by KishanVyas308** [comment]
Absolutely!  thanks for the kind words about the article breakdown. I'm glad it helped clear up some of the outlining process for this open-source project.

That's a fantastic idea to collaborate on making the article even more detailed and awesome. I'd be happy to work with you on it.  Let's see if [ @codexive-zech ]  is up for brainstorming too – the more perspectives, the better!

By the way, I'm also a developer, so I'm familiar with the coding side of things. If there are any technical aspects that need tackling, I'm happy to jump in and help out there as well.

Just to confirm, should we focus entirely on the open-source project aspects and tailor the article to that specifically?

**Comment by lambeboluwatife** [comment]
> Absolutely!  thanks for the kind words about the article breakdown. I'm glad it helped clear up some of the outlining process for this open-source project.
> 
> That's a fantastic idea to collaborate on making the article even more detailed and awesome. I'd be happy to work with you on it.  Let's see if [ @codexive-zech ]  is up for brainstorming too – the more perspectives, the better!
> 
> By the way, I'm also a developer, so I'm familiar with the coding side of things. If there are any technical aspects that need tackling, I'm happy to jump in and help out there as well.
> 
> Just to confirm, should we focus entirely on the open-source project aspects and tailor the article to that specifically? 

Yes, please focus on the open-source project aspects of it. There are still some API endpoints that We are still gonna use for the project.

And please feel free to check the project live site and the codebase to see if there's any area you'll like to contribute be it refactoring of codes, adding new features or spotting and fixing a bug. Just create a detailed issue on what you want to do and how you want to do it, and it will be assigned to you.

Thanks for your contribution.
@Kishan-Vyas

**Comment by codexive-zech** [comment]
@Kishan-Vyas my idea for the article is that it will help sell the open source project to developers making it easy for them to generate an API and contribute the little they can even if they weren't up for the task. 

The article will have to be strictly for this project, selling it out to Developer so they can easily generate an API and contribute.

Are you on the Discord server I would like to send you a DM so we could hop on a call and discuss about it before we commerce writing.

Note: they are still some basic article idea I have this open source project that with I will discuss with @lambeboluwatife 
once this is out of the way. So we got time to learn alot from each other. Am also a Developer.
