### ISSUE TITLE
Navbar icon issue (LBDFlix)

### ISSUE THREAD

**Issue by Himanshuraj2918** [lambeboluwatife/lbdflix#25]
When we scroll page up an down, but the navbar  icon is fixed at that point.....

**Comment by lambeboluwatife** [comment]
Nice issue 
But can you make the issue more detailed and if possible add an image of the issue.
Thank you

**Comment by Himanshuraj2918** [comment]
![Screenshot 2024-04-20 012254](https://github.com/lambeboluwatife/lbdflix/assets/98225176/3762b68d-1506-4117-92f9-51fcdac41d9c)
![Screenshot 2024-04-20 012209](https://github.com/lambeboluwatife/lbdflix/assets/98225176/38292d05-fc22-4b78-930d-ab2bb0353648)

**Comment by Himanshuraj2918** [comment]
In second image your navbar icon is conflict with scargiver

**Comment by lambeboluwatife** [comment]
> In second image your navbar icon is conflict with scargiver 

What do you mean?

**Comment by Himanshuraj2918** [comment]
![Screenshot 2024-04-20 012209](https://github.com/lambeboluwatife/lbdflix/assets/98225176/98dee7e1-2afc-458c-abcb-7f868d280150)


### The area that marked in blue color.

**Comment by lambeboluwatife** [comment]
Okay 
Do you want to work on this?

**Comment by lambeboluwatife** [comment]
@Himanshuraj2918 please resend the images. They are not showing. Thank you
