### ISSUE TITLE
Footer Missing

### ISSUE THREAD

**Issue by lambeboluwatife** [lambeboluwatife/lbdflix#32]
The entire application doesn't have a footer.
![image](https://github.com/lambeboluwatife/lbdflix/assets/40843759/6e4b8d51-b651-426d-9604-3280439c73ea)

**Comment by GeorgiosDrivas** [comment]
Hello @lambeboluwatife ! I would like to work on this issue. Provide information about what content you want the footer to have, and styling. Thank you in advance!

**Comment by lambeboluwatife** [comment]
> Hello @lambeboluwatife ! I would like to work on this issue. Provide information about what content you want the footer to have, and styling. Thank you in advance!

Okay @GeorgiosDrivas, I'll assign it to you and the details will be sent soon.
Thank you

**Comment by lambeboluwatife** [comment]
@GeorgiosDrivas so the footer should be a simple one. It should contain the project name as a link to the home page and also links to the trending page and the theater page and a link to the GitHub repo.
With this information, surprise me 😅😅😅

**Comment by GeorgiosDrivas** [comment]
@lambeboluwatife  Great! I will start working on it and inform you when it's ready

**Comment by lambeboluwatife** [comment]
> @lambeboluwatife  Great! I will start working on it and inform you when it's ready

Okay
