### ISSUE TITLE
Created an index.js file for easier component import/export and resolved import errors

### ISSUE THREAD

**Issue by Saber1Y** [lambeboluwatife/lbdflix#46]
Issue Description
Context:
To streamline the process of importing components in our project, I created an index.js file in the components directory. This file is intended to centralize the import and export of all components, making it easier to manage and use them throughout the project.

.

Additional Information
If anyone encounters a similar issue, please ensure the following:

All components are correctly imported and exported in index.js.
Components are imported using named exports in other files.
Feel free to reach out if further clarification or assistance is needed.

**Comment by lambeboluwatife** [comment]
Good 
Thank you but you also have to provide a detailed description of the issue and possibly how to fix it.

So sorry for the stress.
I just want to make the project easier for contributors.

**Comment by Saber1Y** [comment]
Sure!     

There is a first time for everything
