### ISSUE TITLE
Navbar Responsiveness

### ISSUE THREAD

**Issue by lambeboluwatife** [lambeboluwatife/lbdflix#58]
The navbar isn't responsive for smaller screens.
![image](https://github.com/user-attachments/assets/cc756ad3-ab07-42db-bb7b-c10057baa0bc)

**Comment by sowunmi-mayowa** [comment]
I’ll fix this chief

**Comment by lambeboluwatife** [comment]
> I’ll fix this chief 

Sorry, I already fix this, I forgot to close the issue. But you can check the site for any other thing that needs fixing or any features you want to add. Just create a detailed issue on it and it will be assigned to you.

**Comment by sowunmi-mayowa** [comment]
Alright no problem chief
